name: EAS Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Choose the build platform'
        required: true
        type: choice
        options:
          - android
          - ios
      profile:
        description: 'Choose the build profile'
        required: true
        type: choice
        options:
          - preview
          - production
      project_id:
        description: 'Enter the EAS project ID'
        required: true
        type: string

jobs:
  eas-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Initialize EAS project
        working-directory: frontend
        run: |
          eas init --id ${{ github.event.inputs.project_id }} --non-interactive

      - name: Run EAS build
        working-directory: frontend
        run: |
          eas build --platform ${{ github.event.inputs.platform }} --profile ${{ github.event.inputs.profile }} --non-interactive
